POST http://localhost:9328/V3/StudentNames/Insert/AsIs
Content-Type: application/json

{
  "StudentName": "",
  "Mobile": "",
  "email": "",
  "CollegeName": "",
  "Country": "",
  "EntranceRank": "",
  "YearPassOut": "",
  "Back_logs": "",
  "RollNumber": "",
  "file": "",
  "GitLink": ""
}